server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: root
  application:
    name: async_spring_boot
  sql:
    init:
      mode: never

  #To display SQL At console
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update